base-url:               http://site.meenta.io/
highlighter:            false
markdown:               markdown
permalink:              pretty
site-title:             Meenta.io
bio-fullname:           Stephan Smith
bio-nickname:           d1b1
bio-email-address:      stephan@meenta.ion
bio-phone-number:       +1 617 953 7947
description:            Science Equipment Sharing Service for Next Generation Sequencing.
include:                [ 'team' ]
exclude:                [ 'source', 'team', 'assets' ]
plugins:
  - jekyll-sitemap
