base-url:               http://site.meenta.io/
highlighter:            false
markdown:               kramdown
permalink:              pretty
site-title:             Meenta.io
bio-fullname:           Stephan Smith
bio-nickname:           d1b1
bio-email-address:      stephan@meenta.ion
bio-phone-number:       +1 617 953 7947
description:            Science Equipment Sharing Service for Next Generation Sequencing.
include:                [ 'faqs' ]
exclude:                [ 'source', 'team', 'assets', 'dist' ]
collections:
  faqs:
    output: true
    title: FAQs
    permalink: /faqs/:path/
  team:
    output: false
    title: Team
    permalink: /team/:path/
plugins:
  - jekyll-sitemap
